export const products = [
    { id: 1, name: 'UltraSoft Pillow', price: 25 },
    { id: 2, name: 'EcoClean Detergent', price: 15 },
    { id: 3, name: 'Smart LED Bulb', price: 18 },
    { id: 4, name: 'Vintage Clock', price: 40 },
    { id: 5, name: 'Bluetooth Speaker', price: 55 },
    { id: 6, name: 'Organic Honey Jar', price: 22 },
    { id: 7, name: 'Aroma Oil Diffuser', price: 30 },
    { id: 8, name: 'Wireless Charger', price: 35 },
    { id: 9, name: 'Bamboo Toothbrush', price: 8 },
    { id: 10, name: 'Ceramic Plant Pot', price: 16 },
    { id: 11, name: 'Leather Wallet', price: 45 },
    { id: 12, name: 'Electric Kettle', price: 50 },
    { id: 13, name: 'Portable Blender', price: 32 },
    { id: 14, name: 'Reusable Water Bottle', price: 12 },
    { id: 15, name: 'Anti-Glare Glasses', price: 28 },
    { id: 16, name: 'Memory Foam Mattress', price: 250 },
    { id: 17, name: 'Yoga Mat', price: 20 },
    { id: 18, name: 'Travel Backpack', price: 60 },
    { id: 19, name: 'Noise-Canceling Headphones', price: 75 },
    { id: 20, name: 'Espresso Maker', price: 90 },
    { id: 21, name: 'Wireless Earbuds', price: 50 },
    { id: 22, name: 'Smart Watch', price: 110 },
    { id: 23, name: 'Stainless Steel Mug', price: 15 },
    { id: 24, name: 'Handmade Soap Set', price: 18 },
    { id: 25, name: 'Fitness Tracker', price: 85 },
    { id: 26, name: 'Kitchen Knife Set', price: 45 },
    { id: 27, name: 'Mini Projector', price: 130 },
    { id: 28, name: 'Weighted Blanket', price: 70 },
    { id: 29, name: 'Scented Candle', price: 12 },
    { id: 30, name: 'Gaming Mouse', price: 25 },
    { id: 31, name: 'Electric Toothbrush', price: 55 },
    { id: 32, name: 'Portable Power Bank', price: 30 },
    { id: 33, name: 'Thermal Insulated Lunch Bag', price: 22 },
    { id: 34, name: 'Adjustable Standing Desk', price: 200 },
    { id: 35, name: 'LED Makeup Mirror', price: 35 },
    { id: 36, name: 'Laptop Stand', price: 40 },
    { id: 37, name: 'Smartphone Ring Light', price: 20 },
    { id: 38, name: 'Foldable Bluetooth Keyboard', price: 28 },
    { id: 39, name: 'WiFi Range Extender', price: 45 },
    { id: 40, name: 'Pet Water Fountain', price: 25 },
    { id: 41, name: 'Digital Meat Thermometer', price: 18 },
    { id: 42, name: 'Multi-Tool Kit', price: 50 },
    { id: 43, name: 'Adjustable Dumbbell', price: 70 },
    { id: 44, name: 'Facial Cleansing Brush', price: 20 },
    { id: 45, name: 'Handheld Vacuum Cleaner', price: 55 },
    { id: 46, name: 'Desk Organizer', price: 10 },
    { id: 47, name: 'Retro Bluetooth Radio', price: 65 },
    { id: 48, name: 'Fitness Jump Rope', price: 15 },
    { id: 49, name: 'Electric Heating Pad', price: 30 },
    { id: 50, name: 'Silk Pillowcase', price: 22 },
    { id: 51, name: 'UV Phone Sanitizer', price: 40 },
    { id: 52, name: 'Leather Journal', price: 18 },
    { id: 53, name: 'Home Security Camera', price: 70 },
    { id: 54, name: 'Collapsible Storage Box', price: 12 },
    { id: 55, name: 'Inflatable Sofa', price: 45 },
    { id: 56, name: 'Smart Plug', price: 15 },
    { id: 57, name: 'Electric Milk Frother', price: 25 },
    { id: 58, name: 'Cordless Hair Clipper', price: 35 },
    { id: 59, name: 'Sustainable Bamboo Towel', price: 18 },
    { id: 60, name: 'Magnetic Car Phone Mount', price: 10 },
  ];
  